FROM node:20

ARG VITE_POSTIVA_API_KEY
ENV VITE_POSTIVA_API_KEY=$VITE_POSTIVA_API_KEY
ARG VITE_POSTIVA_WORKSPACE_ID
ENV VITE_POSTIVA_WORKSPACE_ID=$VITE_POSTIVA_WORKSPACE_ID

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run build
CMD [ "npm", "run", "preview" ]