version: "3"
services:
  docs:
    build: .
    ports:
      - "6000:3000"
    networks:
      - dokploy-network
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.nuxtstarter.entrypoints=websecure"
     - "traefik.http.routers.nuxtstarter.tls.certResolver=letsencrypt"
     - "traefik.http.routers.nuxtstarter.rule=Host(`nuxt-starter.postiva.app`)"
     - "traefik.http.services.nuxtstarter.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true